<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseHour extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hour');
        $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('time', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
    }

    public function setUp()
    {
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}